//User Roles
export const USER_ROLES = {
  ADMIN: "ADMIN",
  DRIVER: "DRIVER",
};

//Vehicle Status
export const VEHICLE_STATUS = {
  AVAILABLE: "AVAILABLE",
  ON_TRIP: "ON_TRIP",
  UNDER_MAINTENANCE: "UNDER_MAINTENANCE",
  OUT_OF_SERVICE: "OUT_OF_SERVICE",
};

//Trailer Types
export const TRAILER_TYPES = {
  FLATBED: "FLATBED",
  REFRIGERATED: "REFRIGERATED",
  TANKER: "TANKER",
  CONTAINER: "CONTAINER",
  LOWBOY: "LOWBOY",
  DRY_VAN: "DRY_VAN",
};

//HTTP Status Codes
export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};
